name: Send Slack Message

on:
  schedule:
    - cron: '30 3 * * *'  # Runs every day at 3:30 AM UTC (9 AM IST)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup Go environment
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Run Test and Send Slack Message
      run: go run prow_summary.go
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        URL: ${{ secrets.URL }}
        PROW_URL: ${{ secrets.PROW_URL }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
