name: Send Slack Message

on:
  schedule:
    - cron: '0 3 * * *' # This corresponds to 9AM IST (UTC+5:30)

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Run Go script
      run: go run prow_summary.go
      env:
        URL: ${{ secrets.URL }}
        PROW_URL: ${{ secrets.PROW_URL }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        TOKEN: ${{ secrets.SLACK_TOKEN }}
